INSERT INTO `role` (`id`, `name`) VALUES (1, 'ADMIN') ON DUPLICATE KEY UPDATE ID = 1;
INSERT INTO `role` (`id`, `name`) VALUES (2, 'SUPER_USER') ON DUPLICATE KEY UPDATE ID = 2;
INSERT INTO `role` (`id`, `name`) VALUES (3, 'USER') ON DUPLICATE KEY UPDATE ID = 3;